Update zh_cn localization
Globox1997/LevelZ pull request #69
Opened 2021-12-15 12:26 UTC by RawPineapple

- Refined overall translation
- Changed formatting so they look neat in game GUI
- Added missing translations

problem: some block/Entity/item names are still displayed in English due to being passed by identifiers. Nothing I can do on the language file side.

2021-12-15 16:05 UTC, LangYueMc commented on src/main/resources/assets/levelz/lang/zh_cn.json
> +  "item.levelz.strange_potion": "奇怪药水",
神奇药水会好些

2021-12-15 16:14 UTC, LangYueMc commented on src/main/resources/assets/levelz/lang/zh_cn.json
> +  "text.autoconfig.levelz.option.disableMobFarms": "经由刷怪笼生成的怪物不给予经验值",
这块我看了代码，并不是刷怪笼，而是一个区块里杀怪超过 5 只，就会不掉任何东西，当然刷怪笼会触发更频繁，所以你可能是误解了。

2021-12-15 16:16 UTC, LangYueMc requested changes
翻译有部分错误，建议修改后再 PR

2021-12-15 16:21 UTC, LangYueMc commented on src/main/resources/assets/levelz/lang/zh_cn.json
> +  "text.autoconfig.levelz.option.luckSurviveChance": "幸存致死伤害几率",
语法并不通顺，建议翻译为 “免疫致死伤害几率”

2021-12-15 17:07 UTC, RawPineapple commented
Fixed incorrect translations
Taking suggestions by @LangYueMc

2021-12-16 18:28 UTC, RawPineapple commented
tested in game, not seeing any translation error. You may merge this safely now.

2021-12-17 14:04 UTC, Globox1997 commented
Thanks for contributing :)

2021-12-17 14:04 UTC, merged